name: pomodoro_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
