name: pomodoro_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  uuid: ^4.5.2
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon.png

